#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i "50i\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n\t" /etc/nginx/sites-available/default

sudo service nginx restart
