#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html

new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        #add_header X-Served-By 990e43864b75;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
        error_page 404 /error_404.html;
        location = /error_404.html {
                internal;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"
sudo echo "Ceci n'est pas une page" > /var/www/html/error_404.html

sudo echo "$new_config" > /etc/nginx/sites-available/default

service nginx start
