#!/usr/bin/env bash
# script install and configure HAproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 37801-web-01 54.160.120.236:80 check\n\tserver 37801-web-02 100.25.165.214:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
