#!/usr/bin/env bash
# script install and configure HAproxy

sudo apt update
sudo apt install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 37801-web-01 54.160.120.236 check\n\tserver 37801-web-02 100.25.165.214 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
